/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package RestFul.practica7;


import kong.unirest.GenericType;
import kong.unirest.Unirest;

import java.util.List;
import java.util.Scanner;


public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        listarEstudiantes();
        consultarEstudiante(20011136);
//        Estudiante est=new Estudiante(12312,"Elias","Rodriguez");
//        crearEstudiante(est);
        eliminarEstudiante(1231);
//        Scanner entrada = new Scanner(System.in);
//        Scanner leerN = new Scanner(System.in);
//        int n=1;
//        while (n!=0) {
//            System.out.println("Digite la opción que desea:");
//            System.out.println("Digite 1 para Listar Estudiantes:");
//            System.out.println("Digite 2 para Consultar un Estudiante:");
//            System.out.println("Digite 3 para Crear un Estudiante:");
//            System.out.println("Digite 4 para borrar un Estudiante:");
//            n= Integer.parseInt(leerN.nextLine());
//            if (n==1){
//                listarEstudiantes();
//            }
//            else if( n==2){
//                System.out.println("Escriba la matricula:");
//                int matri=Integer.parseInt(entrada.nextLine());
//                consultarEstudiante(matri);
//            }
//            else if (n==3){
//                System.out.println("Escriba la matricula:");
//                int matri= Integer.parseInt(entrada.nextLine());
//                System.out.println("Escriba el nombre:");
//                String nom= entrada.nextLine();
//                System.out.println("Escriba la carrera:");
//                String carr= entrada.nextLine();
//                Estudiante temp= new Estudiante(matri,nom,carr);
//                crearEstudiante(temp);
//            }
//            else if (n==4){
//                System.out.println("Escriba la matricula:");
//                int matri=Integer.parseInt(entrada.nextLine());
//                eliminarEstudiante(matri);
//            }
//        }

    }
    public static void listarEstudiantes(){
        List<Estudiante> listaEstudiantes = Unirest.get("http://localhost:7000/api/estudiante")
                .asObject(new GenericType<List<Estudiante>>() {
                })
                .getBody();
        for (Estudiante estud:listaEstudiantes) {
            System.out.println("Matricula"+" "+ estud.getMatricula());
            System.out.println("Nombre"+" "+ estud.getNombre());
            System.out.println("Carrera"+" "+ estud.getCarrera());
        }
    }
    public static void consultarEstudiante(int matricula){
       Estudiante estud=Unirest.get("http://localhost:7000/api/estudiante/{matricula}")
                .routeParam("matricula", String.valueOf(matricula))
                .asObject(new GenericType<Estudiante>() {
                }).getBody();
        System.out.println("Matricula"+" "+ estud.getMatricula());
        System.out.println("Nombre"+" "+ estud.getNombre());
        System.out.println("Carrera"+" "+ estud.getCarrera());
    }
    public static void eliminarEstudiante(int matricula){
        Unirest.delete("http://localhost:7000/api/estudiante/{matricula}")
                .routeParam("matricula",String.valueOf(matricula))
                .asEmpty();
    }
    public static void crearEstudiante(Estudiante estudiante){
        Unirest.post("http://localhost:7000/api/estudiante")
                .header("Content-Type", "application/json")
                .body(estudiante)
                .asEmpty();
    }
}
